title: [Darryen Sands]
description: [A website to host Darryen's projects.]
logo: /assets/img/logo.png
theme: jekyll-theme-minimal
google_analytics:
show_downloads: false
repository: DarryenSands/DarryenSands.github.io
plugins:
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-redirect-from
    - github-pages
    
collections:
  posts:
    output: true
    defaults:
      values:
        tags: []