title: [Darryen Sands]
description: [A website to host Darryen's projects.]
logo: /assets/img/logo.png
theme: jekyll-theme-minimal  
show_downloads: false
repository: DarryenSands/DarryenSands.github.io
plugins:
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-redirect-from
    - github-pages
    - jektex
    - d3-rails